<?php

namespace Esprit\ApiBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUsername($username)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u FROM EspritApiBundle:fos_user u WHERE u.username=:username'
            )->setParameter('email', $username)
            ->getResult();
    }
}
